kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blueno-nfs
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 190Gi # Needs to be slightly smaller than the data volume