apiVersion: v1
kind: Service
metadata:
  name: blueno-db
spec:
  ports:
    - port: 5432
  selector:
    app: blueno-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blueno-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blueno-db
  template:
    metadata:
      labels:
        app: blueno-db
    spec:
      # Putting the NFS server and DB on the same node leads to slow performance
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: nfs-server-provisioner
              weight: 100
      containers:
        - name: blueno-db
          image: postgres:11
          envFrom:
            - secretRef:
                name: blueno-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg
              subPath: postgres
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0m
              memory: 70Mi
      volumes:
        - name: pg
          persistentVolumeClaim:
            claimName: blueno-db
  strategy:
    type: Recreate